feat(PhotosEndpoint): first files for photos but broken
ESGI-69/challenge-flutter-go pull request #112
Opened 2024-06-23 12:13 UTC by sguenier

2024-06-23 15:40 UTC, Timdev0 approved these changes

2024-06-23 19:13 UTC, mrpinkcat requested changes

2024-06-23 19:13 UTC, mrpinkcat commented on go/api/handlers/photo.go
> +
```suggestion
  // ICI
```

Il faut vérifier que la photo appartient bien au trip

2024-06-23 19:13 UTC, mrpinkcat commented on go/api/handlers/photo.go
> +	}
```suggestion
	}
	// ICI
```

Pareil, il faut vérifier que la photo appartient bien au trip et que le mec est bien l'uploader de la photo

2024-06-23 19:13 UTC, mrpinkcat commented on go/api/server.go
> +	tripPhotosRoutes.DELETE("/:photoID", middlewares.UserHasTripEditRight, photoHandler.DeletePhotoFromTrip)
```suggestion
	tripPhotosRoutes.DELETE("/:photoID", middlewares.UserIsTripOwner, photoHandler.DeletePhotoFromTrip)
```

2024-06-23 19:13 UTC, mrpinkcat commented on go/models/photo.go
> +}
Il faudrait rajouter l'author

2024-06-23 19:13 UTC, mrpinkcat commented on go/models/photo.go
> +		log.Println(err)
utilise le logger

2024-06-24 15:23 UTC, mrpinkcat approved these changes

2024-06-24 15:23 UTC, merged