feat(getImageFromAddress): add googleMapsWrapper file in utils
ESGI-69/challenge-flutter-go pull request #113
Opened 2024-06-23 18:45 UTC by ycenta

2024-07-03 10:20 UTC, mrpinkcat requested changes

2024-07-03 10:20 UTC, mrpinkcat commented on go/.env.example
> +GOOGLE_API_KEY=APIKEY
Il faut que je mette ca dans les secret k8s je resolve quand c'est bon

2024-07-03 12:36 UTC, mrpinkcat requested changes
Ca fait quoi si la clé d'api n'est pas valable ou qu'elle en trouve pas d'image ? Si jamais la clé d'api pète avant la soutenance il faut qu'on fallback automatiquement sur une image de placeholder.

C'est dommage de pas avoir fait le flutter pour ca aussi

Envois moi la clé d'api je la passerais a k8s

2024-07-03 12:36 UTC, mrpinkcat commented on go/api/handlers/trip.go
> +
```suggestion
```

2024-07-03 12:36 UTC, mrpinkcat commented on go/api/handlers/trip.go
> +			}
Tu peux pas passer ca dans un utils `saveBanner` par exemple ?

2024-07-03 12:43 UTC, mrpinkcat commented
Volumes et clé d'api appliqué sur k8s, prèt a merger après les requested changes

2024-07-03 18:12 UTC, mrpinkcat commented
Reping moi, j'ai du remove la config pour mettre autre chose

2024-07-04 10:59 UTC, mrpinkcat requested changes

2024-07-04 10:59 UTC, mrpinkcat commented on move_together_app/lib/core/models/trip.dart
> +      photoUrl: json['photoUrl'],
```suggestion
      photoUrl: json['photoUrl'] == null ? 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/260px-Tour_Eiffel_Wikimedia_Commons.jpg': dotenv.env['API_ADDRESS'] + "/banner/" + json['photoUrl'],
```

Tu peux mettre l'image par défaut ici comme ca t'as pas a faire de if dans les composants

2024-07-04 10:59 UTC, mrpinkcat commented on move_together_app/lib/core/models/trip.dart
> +  }
```suggestion
    required this.photoUrl,
    });
```

Du coup tu peux mettre la prop en `required`

2024-07-04 10:59 UTC, mrpinkcat commented on move_together_app/lib/core/models/trip.dart
> +  final String? photoUrl;
```suggestion
  final String photoUrl;
```

2024-07-04 10:59 UTC, mrpinkcat commented on move_together_app/lib/Home/home_screen.dart
> +                        imageUrl: imageUrlToUse,
```suggestion
                        imageUrl: trip.photoUrl,
```

Comme maintenant t'as un default dans le model, tu peux directement lui passer `photoUrl`. La condition se fait dans le model

2024-07-04 10:59 UTC, mrpinkcat commented on move_together_app/lib/Home/home_screen.dart
> +                      }
```suggestion
```

Comme maintenant t'as un default dans le model, plus besoin de la condition ici. Elle est déjà faite dans le model

2024-07-04 12:50 UTC, ycenta commented on move_together_app/lib/core/models/trip.dart
> +      photoUrl: json['photoUrl'],
au final je fais coté backend (avec une image stockée sur le server)

2024-07-04 12:51 UTC, ycenta commented on move_together_app/lib/core/models/trip.dart
> +  }
au final j'enleve la valeur "photoUrl" du model vu qu'elle n'est plus renvoyé coté backend

2024-07-04 12:51 UTC, ycenta commented on move_together_app/lib/core/models/trip.dart
> +  final String? photoUrl;
au final j'enleve la valeur "photoUrl" du model vu qu'elle n'est plus renvoyé coté backend

2024-07-04 12:52 UTC, ycenta commented on move_together_app/lib/Home/home_screen.dart
> +                        imageUrl: imageUrlToUse,
au final j'enleve la valeur "photoUrl" du model vu qu'elle n'est plus renvoyé coté backend

2024-07-04 12:52 UTC, ycenta commented on move_together_app/lib/Home/home_screen.dart
> +                      }
au final j'enleve la valeur "photoUrl" du model vu qu'elle n'est plus renvoyé coté backend

2024-07-04 13:09 UTC, mrpinkcat approved these changes

2024-07-04 13:09 UTC, merged