feat(transports): add endpoints, migrations and functions to add or r…
ESGI-69/challenge-flutter-go pull request #6
Opened 2024-05-20 21:25 UTC by ycenta

add or remove transport to trips :
Endpoints : 

POST : http://localhost:8080/trips/:TripId/transport : 
**requires bearer token**
example body : 
```
{
	"TransportType":"car",
	"StartAddress": "paris",
	"EndAddress": "Lyon",
	"StartDate":"2022-01-01T00:00:00Z",
	"EndDate":"2022-01-01T00:00:00Z"
}
```
DELETE http://localhost:8080/trips/:TripId/transport/:TransportId
**requires bearer token**

2024-05-24 09:55 UTC, mrpinkcat commented on go/models/models.go
> +	TripID        uint
Tu as oublié la référence vers le type `Trip`. Regarde ce qui a été fait plus haut avec l'owner.

2024-05-24 09:55 UTC, mrpinkcat requested changes
Juste la petit référence vers le trip et c'est good

2024-05-28 10:32 UTC, ycenta commented
J'ai modifié la logique du repo/handler pour le trip pour récuperer l'id du transport quand il est crée (il renvoyait 0 avant)

2024-05-28 12:28 UTC, mrpinkcat approved these changes

2024-05-28 12:29 UTC, merged