43 API endpoint pour l'upload de document sur un trip
ESGI-69/challenge-flutter-go pull request #69
Opened 2024-06-13 16:15 UTC by Timdev0

2024-06-14 17:47 UTC, mrpinkcat requested changes
Ajouter PV PVC volume dans le dossier k8s pour les uploads

2024-06-14 23:34 UTC, mrpinkcat requested changes

2024-06-14 23:34 UTC, mrpinkcat commented on go/api/handlers/document.go
> +	file, errFile := context.FormFile("document")
Ca peut etre une bonne chose de limiter la taille de l'upload (et de compresser le fichier peut etre)

2024-06-14 23:34 UTC, mrpinkcat commented on go/api/handlers/document.go
> +		Trip:        trip,
```suggestion
	var document = models.Document{
		Title:       title,
		Description: description,
		TripID:        tripId,
```

Je crois que ca marche comme ca

2024-06-14 23:34 UTC, mrpinkcat commented on go/models/document.go
> +	Description string `gorm:"not null"`
```suggestion
	Description string
```

Je suis pas sur pour le not null sur la description ?

Je pense pas qu'avoir une description sur un passport serve à grand chose par exemple

2024-06-14 23:34 UTC, mrpinkcat commented on go/api/requests/document.go
> +	Description string                `json:"description" binding:"required"`
```suggestion
	Description string                `json:"description"`
```
Je suis pas sur pour le binding:"required" sur la description ?

Je pense pas qu'avoir une description sur un passport serve à grand chose par exemple

2024-06-14 23:34 UTC, mrpinkcat commented on go/repository/document.go
> +	return result.Error
```suggestion
func (d *DocumentRepository) DeleteDocument(trip models.Trip, documentID uint) error {
	return d.Database.Delete(&models.Document{}, documentID).Error
```
Tu peux faire tenir tout ca en une ligne

2024-06-14 23:34 UTC, mrpinkcat commented on k8s/backend-all.yaml
> +      storage: 1Gi
```suggestion
      storage: 20Gi
```

C'est peut etre plus acceptable pour de l'upload de fichier

2024-06-14 23:34 UTC, mrpinkcat commented on go/models/document.go
Il faudrait rajouter un hook d'afterDelete qui supprime de fichier du disque

2024-06-15 12:06 UTC, mrpinkcat requested changes

2024-06-15 12:06 UTC, mrpinkcat commented on go/repository/document.go
> +	return d.Database.Delete(&document).Error
```suggestion
	result := d.Database.Delete(&models.document{}, documentID)
	if result.RowsAffected == 0 {
		return gorm.ErrRecordNotFound
	}
	return result.Error
```

T'as un exemple pour la suppression d'un transport ici https://github.com/ESGI-69/challenge-flutter-go/blob/4f96bc4db010d6503da69f3f4ca7c843bb827d97/go/repository/transport.go#L23-L30

Comme ça, qu'**une seule query** sur la base de donnée pour une suppression. À la place de 2, une pour récupérer le document et une pour le supprimer.

2024-06-15 12:06 UTC, mrpinkcat commented on go/api/handlers/document.go
> +	documents, err := handler.Repository.GetDocuments(trip)
```suggestion
	documents, err := handler.Repository.GetDocuments(tripId)
```

Pas besoin d'aller recherchee le trip pour le passer au repo, on est déjà assuré qu'il exsite dans les middlewares. Il faut modifier le repo aussi.

2024-06-15 12:06 UTC, mrpinkcat commented on go/repository/document.go
> +}
```suggestion
func (d *DocumentRepository) GetDocuments(tripId string) (documents []models.Document, err error) {
	err = d.Database.Model(&models.Document{}).Where("trip_id = ?", tripId).Find(&documents).Error
	return
}
```

Pour faire suite à la review dans le repo

2024-06-15 12:06 UTC, mrpinkcat commented on go/repository/document.go
> +func (d *DocumentRepository) DeleteDocument(trip models.Trip, documentID uint) (err error) {
```suggestion
func (d *DocumentRepository) Delete(documentID uint) (err error) {
```

Pourquoi t'as le trip ici ?

Et pas besoin de spécifier qu'on delete un document, on est déjà dans le repo

2024-06-15 12:06 UTC, mrpinkcat commented on go/api/handlers/document.go
> +	}
```suggestion
	var document = models.Document{
		Title:       title,
		Description: description,
		TripID:      tripId,
		Path:        filePath,
	}
```

Une query sur la database en moins

2024-06-15 12:06 UTC, mrpinkcat commented on go/api/handlers/document.go
> +	err := handler.Repository.DeleteDocument(trip, document.ID)
```suggestion
	document, errDoc := handler.Repository.Get(documentID)
	if errDoc != nil {
		errorHandlers.HandleGormErrors(errDoc, context)
		return
	}

	err := handler.Repository.Delete(document.ID)
```

Pas besoin du trip ici

2024-06-15 14:05 UTC, Timdev0 commented on go/repository/document.go
> +	return d.Database.Delete(&document).Error
le hook recupere pas le doc meme avec ca

2024-06-15 16:01 UTC, mrpinkcat commented
Je vais tester et déployer les PV sur le vps avant de merge

2024-06-17 11:25 UTC, mrpinkcat approved these changes

2024-06-17 11:29 UTC, merged