40 create trip page flutter
ESGI-69/challenge-flutter-go pull request #82
Opened 2024-06-17 13:27 UTC by ycenta

2024-06-18 16:05 UTC, ycenta commented
<img width="233" alt="Capture d’écran 2024-06-18 à 18 01 13" src="https://github.com/ESGI-69/challenge-flutter-go/assets/40060168/2f87f55c-de16-4756-9980-2047f7454c69">
[recordflutterTRIPCREATION.webm](https://github.com/ESGI-69/challenge-flutter-go/assets/40060168/2244e07c-7ee1-4665-9a51-fc77e11daa95)

Je resolve les conflits et ça part en review

2024-06-18 16:25 UTC, mrpinkcat requested changes
J'ai déjà fait les blocs pour les trips merge ce que t'as fait dans l'existant.

C'est pour ca qu'il vaut mieux rebase avant de coder 🤷‍♂️

2024-06-18 22:05 UTC, mrpinkcat requested changes

2024-06-18 22:05 UTC, mrpinkcat commented on move_together_app/lib/core/services/api_services.dart
> +    String formattedEndDate = DateFormat("yyyy-MM-ddTHH:mm:ss'Z'").format(trip.endDate.toUtc());
```suggestion
    String formattedStartDate = trip.startDate.toIso8601String();
    String formattedEndDate = trip.endDate.toIso8601String();
```

Passe les dates en ISO 8601

2024-06-18 22:05 UTC, mrpinkcat commented on move_together_app/lib/views/trip/create_screen.dart
> +                            ),
Tu peux créer un composant custom pour le `TextField`.

On pourra le réutiliser pour les login et autre à l'avenir

2024-06-18 22:48 UTC, mrpinkcat requested changes
Supprime le package du pubspec

2024-06-19 09:19 UTC, mrpinkcat approved these changes

2024-06-19 10:17 UTC, Timdev0 approved these changes

2024-06-19 11:56 UTC, merged