feat(chat) start screen skeleton
ESGI-69/challenge-flutter-go pull request #96
Opened 2024-06-18 09:14 UTC by Timdev0

2024-06-23 19:06 UTC, mrpinkcat requested changes

2024-06-23 19:06 UTC, mrpinkcat commented on go/api/handlers/chatMessage.go
> +
```suggestion
```

2024-06-23 19:06 UTC, mrpinkcat commented on go/api/handlers/socket.go
> +			fmt.Println("Sending message to client")
Si tu veux log des truc, utilise logger stp https://github.com/ESGI-69/challenge-flutter-go/pull/105

2024-06-23 19:06 UTC, mrpinkcat commented on move_together_app/lib/Chat/chat_app_bar.dart
> +            width: 1.0, // Change this width to match your design
get GPTed

2024-06-23 19:06 UTC, mrpinkcat commented on move_together_app/lib/Chat/chat_screen.dart
> +            ),
```suggestion
            appBar: AppBar(
              title: const Text(tripName),
              leading: const Padding(
                padding: EdgeInsets.only(left: 16.0),
                child: ButtonBack(),
              ),
            ),
```

Je comprends pas pourquoi t'as faire une bar custom

2024-06-23 19:06 UTC, mrpinkcat commented on move_together_app/lib/Chat/chat_screen.dart
> +                : null,
```suggestion
                : sizedBox(height: LA-HEIGHT-DE-LA-LINEAR-PROGESS-INDICATOR),
```

Rajouter une sized box pour éviter cet effet de saut quand tu passe en chargement

2024-06-23 19:06 UTC, mrpinkcat commented on move_together_app/lib/Chat/chat_input.dart
> +                ),
Peut etre que pour l'instant on peut commenter ca, le temps qu'on gère pas l'upload de fichier

2024-06-23 19:06 UTC, mrpinkcat commented on move_together_app/lib/core/services/chat_service.dart
> +    });
```suggestion
    final response = await api.post('/trips/$tripId/chatMessages/', data: message);
```

Ça marche pas comme ça ?

2024-06-23 19:06 UTC, mrpinkcat commented on move_together_app/lib/Chat/chat_bubble.dart
> +                "${message.createdAt.toLocal().toString().split(' ')[0].replaceAll('-', '/').split('/')[2]}/${message.createdAt.toLocal().toString().split(' ')[0].replaceAll('-', '/').split('/')[1]},
```suggestion
              Text("${DateFormat.Md().format(message.createdAt)} ${DateFormat.Hm().format(message.createdAt)}"),
```

C'est plus lisible comme ca nan ?

Utilise la bibliothèque `intl` pour ca https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html

2024-06-23 19:06 UTC, mrpinkcat commented on move_together_app/lib/Chat/chat_body.dart
> +              final isOwnMessage = message.author.id == widget.userId;
```suggestion
              final isOwnMessage = message.isCurrentUserAuthor(context);
```

Utilise le meme système que ce que j'ai fait dans le model des trips.

https://github.com/ESGI-69/challenge-flutter-go/blob/bf1439ac970f333bac21b48233f6b18421288473/move_together_app/lib/core/models/trip.dart#L51-L54

2024-06-23 19:06 UTC, mrpinkcat commented on move_together_app/lib/Chat/chat_body.dart
> +                isOwnMessage: isOwnMessage,
```suggestion
                isOwnMessage: message.isCurrentUserAuthor(context),
```

Du coup tu pourras directement faire ca ici

2024-06-23 20:54 UTC, Timdev0 commented on move_together_app/lib/Chat/chat_input.dart
> +                ),
réel

2024-06-23 20:59 UTC, Timdev0 commented on move_together_app/lib/core/services/chat_service.dart
> +    });
pb de content type pour la request

2024-06-23 21:03 UTC, Timdev0 commented on move_together_app/lib/core/services/chat_service.dart
> +    });
mais je peux ajouter tojson en effet a la place, c'est un oublie de ma part

2024-06-23 21:52 UTC, mrpinkcat requested changes

2024-06-23 21:52 UTC, mrpinkcat commented on move_together_app/lib/core/models/message.dart
> +  }
```suggestion
  bool isCurrentUserAuthor(BuildContext context) {
    return author.isMe(context);
  }
```

Tu peux pas faire ca comme ca ? Comme ca été fait pour les trips avec les participants ?

2024-06-23 21:52 UTC, mrpinkcat commented on move_together_app/lib/Chat/chat_body.dart
> +                isOwnMessage: isOwnMessage
Utilise directement `message.isCurrentUserAuthor(context)` dans la prop, pas besoin de faire une variable pour ca

2024-06-24 06:48 UTC, mrpinkcat approved these changes

2024-06-24 06:48 UTC, merged